# Generated by Django 3.1.7 on 2021-04-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='akun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.akun'),
        ),
        migrations.DeleteModel(
            name='akun',
        ),
    ]
