# Generated by Django 3.1.7 on 2021-04-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_auto_20210426_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurnal',
            old_name='ref',
            new_name='keterangan',
        ),
    ]
